/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Check, Clock3, Laptop, ShieldCheck, WalletCards } from "lucide-react";
import { FaqBlock } from "@/components/FaqBlock";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = { title: "Freelance AI Trainer Opportunities", description: "Apply for managed, paid AI training assignments in coding, mathematics, language, safety and other specialist fields." };
const faq = [
  { question: "Does applying guarantee paid work?", answer: "No. Assignments depend on client demand, skill fit, location or language requirements, assessment results and successful project onboarding." },
  { question: "What equipment do I need?", answer: "You generally need a reliable computer, stable internet connection, a secure and private working environment and the software specified for an assignment." },
  { question: "How are contributors selected?", answer: "Selection may include profile review, identity checks, practical skill assessments, language checks, project-specific calibration and agreement to the relevant terms." },
  { question: "How does payment work?", answer: "Payment terms, basis and timing are disclosed for each assignment before you accept it. Never begin work without written assignment terms." },
  { question: "Is this employment?", answer: "Opportunities are generally structured as independent freelance assignments. The exact relationship and applicable terms are provided before onboarding and may vary by location." },
];

export default function FreelancersPage() {
  return <main><SiteHeader /><section className="freelancer-hero"><div><p className="eyebrow eyebrow-light">For freelance specialists</p><h1>Put your expertise to work training better AI.</h1><p>Join a selective network for paid evaluation, annotation and expert-content assignments—managed with clear instructions, support and quality standards.</p><div><Link className="button button-light" href="/apply">Apply as an AI trainer <ArrowRight size={17} /></Link><a className="button button-ghost" href="#selection">See the selection process</a></div><small>Assignments are not guaranteed and depend on project demand and qualification.</small></div><img src="/media/freelancers-header.jpg" alt="Freelance specialist working on a laptop in a bright workspace" width="1920" height="1280" loading="eager" decoding="async" /></section>
    <section className="freelancer-benefits"><article><BriefcaseBusiness size={23} /><h2>Specialist assignments</h2><p>Work matched to demonstrated skills—not an open bidding marketplace.</p></article><article><Clock3 size={23} /><h2>Flexible projects</h2><p>Availability and expected workload are explained before you accept.</p></article><article><WalletCards size={23} /><h2>Clear payment terms</h2><p>Rates, measurement and payment timing are provided per assignment.</p></article><article><ShieldCheck size={23} /><h2>Managed support</h2><p>Guidance, calibration, feedback and a route for questions.</p></article></section>
    <section className="section assignment-section"><div className="section-heading"><div><p className="eyebrow">Types of work</p><h2>Assignments for different forms of expertise.</h2></div><p>Available categories change with client demand. You will only be invited to work that matches your profile and assessment results.</p></div><div className="assignment-grid"><article><img src="/media/freelancer-video-call.jpg" alt="Specialist joining a remote project briefing" width="612" height="323" loading="lazy" decoding="async" /><h3>Coding & technical</h3><p>Evaluate code, debug solutions, write tests and review technical responses.</p></article><article><img src="/media/freelancer-cafe.jpg" alt="Language professional working from a café" width="612" height="408" loading="lazy" decoding="async" /><h3>Language & writing</h3><p>Assess fluency, relevance, tone, translation and instruction following.</p></article><article><img src="/media/freelancer-hammock.jpg" alt="Remote freelancer working outdoors on a laptop" width="612" height="408" loading="lazy" decoding="async" /><h3>Evaluation & annotation</h3><p>Rank outputs, apply structured labels and document clear judgments.</p></article><article><img src="/media/freelancer-mobile.jpg" alt="Freelancer reviewing information on a mobile phone" width="612" height="408" loading="lazy" decoding="async" /><h3>Safety & user context</h3><p>Test edge cases, policy behaviour and responses in realistic settings.</p></article></div></section>
    <section className="selection-section" id="selection"><div><p className="eyebrow eyebrow-light">Selection process</p><h2>Qualified first. Matched second.</h2><p>ScaleWorkAgency is a managed contributor network. The process protects clients, contributors and the quality of the work.</p></div><ol>{["Submit your profile", "Complete relevant assessments", "Pass project-specific calibration", "Review and accept assignment terms", "Begin monitored production"].map((item, index) => <li key={item}><span>0{index + 1}</span><strong>{item}</strong></li>)}</ol></section>
    <section className="section expectations-section"><div><p className="eyebrow">Before you apply</p><h2>What good contributors bring.</h2></div><div>{["Accurate, honest profile information", "Strong written communication", "Reliable equipment and connectivity", "A private, secure working environment", "Ability to follow detailed instructions", "Respect for confidentiality and data rules", "Availability for calibration and feedback", "Consistent, independently produced work"].map((item) => <span key={item}><Check size={16} /> {item}</span>)}</div></section>
    <section className="freelancer-apply-cta"><div><Laptop size={30} /><p className="eyebrow">Ready to be considered?</p><h2>Tell us where your expertise is strongest.</h2><p>Your application enters a vetting workflow. It is not a promise of immediate work.</p><Link className="button button-dark" href="/apply">Start your application <ArrowRight size={17} /></Link></div></section><FaqBlock items={faq} title="What to know before applying." /><SiteFooter /></main>;
}
