/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ArrowRight, BarChart3, Braces, Check, ChevronRight, Languages, Pi, SearchCheck, ShieldCheck, Sparkles } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { FaqBlock } from "@/components/FaqBlock";
import { industries, insights, services } from "@/lib/site-data";

const homeFaq = [
  { question: "What makes ScaleWorkAgency different from an open contributor platform?", answer: "We operate as a managed delivery partner. Contributor recruitment, qualification, calibration, allocation, review and issue resolution sit inside one accountable project structure." },
  { question: "Can you support a pilot before a larger programme?", answer: "Yes. A bounded pilot is often the best way to validate instructions, quality thresholds, throughput assumptions and the required contributor profile." },
  { question: "How do you handle sensitive data?", answer: "Controls are defined during scoping and may include restricted contributor selection, role-based access, confidentiality terms, minimum-access workflows, secure file exchange and retention rules." },
  { question: "Which languages and domains do you cover?", answer: "Coverage is confirmed for each project based on the exact level of proficiency or professional expertise required. We do not claim coverage until suitable contributors have been identified and qualified." },
];

export default function Home() {
  return (
    <main>
      <SiteHeader />
      <section className="hero-shell" aria-labelledby="hero-title">
        <div className="hero-panel">
          <div className="hero-copy"><p className="eyebrow eyebrow-light"><Sparkles size={14} /> Human intelligence for better AI</p><h1 id="hero-title">Expert-led data.<br />AI you can trust.</h1><p className="hero-lede">Managed teams of carefully qualified specialists who evaluate, annotate and improve the data behind high-performing AI systems.</p><div className="hero-actions"><Link className="button button-light" href="/contact">Discuss a project <ArrowRight size={17} /></Link><Link className="button button-ghost" href="/freelancers">Work as an AI trainer</Link></div><div className="hero-assurance"><ShieldCheck size={18} /><span>Human-reviewed delivery with controlled access and accountable project leadership.</span></div></div>
          <div className="hero-visual"><img src="/media/ai-model-training.webp" alt="AI training concept showing a humanoid robot drawing technical diagrams" width="1100" height="733" loading="eager" decoding="async" /><div className="hero-image-scrim" /><div className="data-card data-card-top"><span>Evaluation layer</span><strong>Human judgment</strong><div className="signal"><i /><i /><i /><i /></div></div><div className="data-card data-card-bottom"><span>Managed workflow</span><div className="progress-row"><i className="is-done" /><i className="is-done" /><i className="is-done" /><i /></div><strong>Review in progress</strong></div></div>
        </div>
        <div className="capability-strip" aria-label="Core capabilities"><span>AI response evaluation</span><span>RLHF workflows</span><span>Data annotation</span><span>Model safety testing</span><span>Expert task creation</span></div>
      </section>

      <section className="proof-band"><div><p className="eyebrow">Built for demanding AI programmes</p><h2>One managed layer between your model team and the human work it depends on.</h2></div><div className="proof-points"><article><strong>Multi-format</strong><span>Text, image, audio, video and structured data</span></article><article><strong>Expert-aware</strong><span>Coding, mathematics, language, safety and professional domains</span></article><article><strong>Quality-led</strong><span>Qualification, calibration, layered review and escalation</span></article></div></section>

      <section className="section section-services" id="services">
        <div className="section-heading"><div><p className="eyebrow">Managed capabilities</p><h2>Human expertise across the AI development lifecycle.</h2></div><p>From high-volume classification to specialist model critique, every programme is designed around the task, contributor profile and quality threshold—not a generic crowd.</p></div>
        <div className="service-grid">{services.slice(0, 6).map((service, index) => <Link className={`service-card service-card-${(index % 3) + 1}`} key={service.slug} href={`/services/${service.slug}`}><span>{service.number}</span><div><h3>{service.title}</h3><p>{service.short}</p></div><ArrowRight size={20} /></Link>)}<Link className="service-card service-card-wide" href="/services/freelance-workforce-management"><span>07</span><div><h3>Freelance workforce management</h3><p>Recruiting, vetting, onboarding, allocation, support and performance control—managed as part of delivery.</p></div><ArrowRight size={20} /></Link></div>
        <div className="section-link"><Link href="/services">Explore every service <ArrowRight size={17} /></Link></div>
      </section>

      <section className="section process-section" id="process"><div className="process-copy"><p className="eyebrow eyebrow-light">Operating model</p><h2>Designed as a system.<br />Managed by people.</h2><p>We convert your outcome into an operating plan with defined roles, instructions, calibration, production controls and delivery checks.</p><Link className="button button-light" href="/how-it-works">See how delivery works <ArrowRight size={17} /></Link></div><div className="process-board">{["Scope", "Recruit & qualify", "Train & calibrate", "Produce", "Review & deliver"].map((item, index) => <div className="process-step" key={item}><span>0{index + 1}</span><div><strong>{item}</strong><small>{["Outcome, data and risk", "Skill and access gates", "Examples and thresholds", "Monitored task delivery", "Final validation and reporting"][index]}</small></div>{index < 4 && <ChevronRight size={18} />}</div>)}<div className="process-status"><span><i /> Active quality signal</span><strong>Standards stay visible from pilot to final delivery.</strong></div></div></section>

      <section className="section expert-section"><div className="section-heading"><div><p className="eyebrow">Specialist workforce</p><h2>The right judgment for the task.</h2></div><p>Contributor profiles are built from the work backwards. Qualifications, assessments and review depth change with the risk and difficulty of the data.</p></div><div className="expert-grid"><article className="expert-card expert-card-feature"><img src="/media/freelancers-header.jpg" alt="Professional working remotely on a laptop" width="1920" height="1280" loading="lazy" decoding="async" /><div><span><Braces size={18} /> Software</span><h3>Developers who can read, test and improve code.</h3></div></article><article className="expert-card"><img src="/media/freelancer-cafe.jpg" alt="Language specialist working on a laptop in a café" width="612" height="408" loading="lazy" decoding="async" /><div><span><Languages size={18} /> Languages</span><h3>Fluent review with cultural context.</h3></div></article><article className="expert-card"><img src="/media/freelancer-video-call.jpg" alt="Technical specialist speaking during a remote video call" width="612" height="323" loading="lazy" decoding="async" /><div><span><Pi size={18} /> Mathematics</span><h3>Reasoning checked by capable specialists.</h3></div></article><article className="expert-card expert-card-text"><SearchCheck size={28} /><span>Safety &amp; policy</span><h3>Structured evaluation for difficult and sensitive outputs.</h3><Link href="/services/expert-ai-training-tasks">Explore expert tasks <ArrowRight size={16} /></Link></article></div></section>

      <section className="quality-panel" id="quality"><div className="quality-intro"><p className="eyebrow eyebrow-light">Quality assurance</p><h2>Quality is controlled at every handoff.</h2><p>We do not wait until final delivery to discover drift. Programme controls are designed before production and reinforced with observable contributor performance.</p><Link href="/quality-security" className="button button-light">Explore quality &amp; security <ArrowRight size={17} /></Link></div><div className="quality-list">{["Qualification tests", "Calibration tasks", "Layered review", "Performance scoring", "Issue resolution"].map((item, index) => <article key={item}><span><Check size={16} /></span><div><small>Control {index + 1}</small><h3>{item}</h3><p>{["Confirm the skills the project actually needs.", "Align judgment before production begins.", "Match review depth to risk and complexity.", "Track patterns, not isolated anecdotes.", "Escalate ambiguity and correct root causes."][index]}</p></div></article>)}</div></section>

      <section className="section industries-section"><div className="section-heading"><div><p className="eyebrow">Where we work</p><h2>Use cases that need more than generic labour.</h2></div><Link className="inline-link" href="/industries">View industries <ArrowRight size={16} /></Link></div><div className="industry-grid">{industries.map((industry, index) => <article key={industry.title}><span>0{index + 1}</span><h3>{industry.title}</h3><p>{industry.text}</p></article>)}</div></section>

      <section className="section case-section"><div className="case-label"><span>Representative engagement</span><p>Illustrative workflow—not presented as completed client work.</p></div><div className="case-main"><div><p className="eyebrow">Coding-model evaluation</p><h2>A specialist review programme for code quality, correctness and instruction following.</h2></div><div className="case-facts"><article><span>Required expertise</span><strong>Software engineering</strong></article><article><span>Workforce model</span><strong>Qualified authors + senior reviewers</strong></article><article><span>Quality controls</span><strong>Calibration, test execution, layered review</strong></article></div></div><div className="case-flow"><span>Rubric design</span><ArrowRight /><span>Skills assessment</span><ArrowRight /><span>Calibrated production</span><ArrowRight /><span>Reviewed dataset</span></div></section>

      <section className="freelancer-callout"><div className="freelancer-callout-image"><img src="/media/freelancer-night-work.jpg" alt="Freelance specialist working on a laptop" width="612" height="408" loading="lazy" decoding="async" /></div><div className="freelancer-callout-copy"><p className="eyebrow">For specialists</p><h2>Use your expertise to help improve AI.</h2><p>Join a selective contributor network for paid evaluation, annotation and expert-content assignments. Opportunities depend on project demand and qualification.</p><div><Link className="button button-dark" href="/apply">Apply as an AI trainer <ArrowRight size={17} /></Link><Link className="inline-link" href="/freelancers">How assignments work <ArrowRight size={16} /></Link></div></div></section>

      <section className="section insights-section"><div className="section-heading"><div><p className="eyebrow">Field notes</p><h2>Practical thinking for AI data teams.</h2></div><Link className="inline-link" href="/insights">View all insights <ArrowRight size={16} /></Link></div><div className="insight-grid">{insights.map((article, index) => <Link key={article.slug} href={`/insights#${article.slug}`} className={`insight-card insight-card-${index + 1}`}><span>{article.category}</span><BarChart3 size={24} /><h3>{article.title}</h3><p>{article.excerpt}</p><small>6 min read <ArrowRight size={14} /></small></Link>)}</div></section>
      <FaqBlock items={homeFaq} />
      <SiteFooter />
    </main>
  );
}
