import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, MessagesSquare, PackageCheck, Search, SlidersHorizontal } from "lucide-react";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = { title: "How It Works", description: "See how ScaleWorkAgency scopes, recruits, calibrates, manages and quality-assures AI training data programmes." };
const steps = [
  { icon: Search, title: "Scope", text: "Align the model objective, data, workflow, risk, quality threshold and practical constraints.", output: "Approved delivery brief" },
  { icon: ClipboardCheck, title: "Recruit & qualify", text: "Define the contributor profile, source suitable specialists and test the capabilities the work needs.", output: "Qualified contributor cohort" },
  { icon: SlidersHorizontal, title: "Train & calibrate", text: "Turn guidelines into examples, calibration tasks, scoring rules and clear escalation paths.", output: "Production-ready team" },
  { icon: MessagesSquare, title: "Produce", text: "Allocate work in controlled batches, support contributors and monitor progress and quality signals.", output: "Reviewed production batches" },
  { icon: PackageCheck, title: "Review & deliver", text: "Complete dataset-level checks, resolve exceptions and package the agreed outputs and reporting.", output: "Validated delivery package" },
];
export default function HowPage() { return <main><SiteHeader /><PageIntro eyebrow="How it works" title="A visible operating model from scope to delivery." text="Every engagement has defined responsibilities, quality gates and escalation paths. The details adapt to your project; accountability does not." /><section className="section delivery-steps">{steps.map((step, index) => { const Icon = step.icon; return <article key={step.title}><span className="step-number">0{index + 1}</span><Icon size={30} /><div><h2>{step.title}</h2><p>{step.text}</p><strong><Check size={15} /> {step.output}</strong></div></article>; })}</section><section className="engagement-options"><div><p className="eyebrow eyebrow-light">Engagement options</p><h2>Start at the level of certainty you have today.</h2></div><div><article><span>01</span><h3>Discovery sprint</h3><p>Clarify the task, rubric, risk and operating assumptions before production.</p></article><article><span>02</span><h3>Controlled pilot</h3><p>Validate quality, workflow and contributor fit on a bounded sample.</p></article><article><span>03</span><h3>Managed programme</h3><p>Move into ongoing delivery with reporting, calibration and capacity management.</p></article></div></section><section className="simple-cta"><div><p className="eyebrow eyebrow-light">Bring us the outcome</p><h2>We’ll help design the human system around it.</h2></div><Link className="button button-light" href="/contact">Plan a project <ArrowRight size={17} /></Link></section><SiteFooter /></main>; }
