import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, FileClock, Fingerprint, KeyRound, RefreshCcw, ShieldAlert, UserCheck } from "lucide-react";
import { FaqBlock } from "@/components/FaqBlock";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = { title: "Quality and Security", description: "Operational controls for contributor vetting, calibration, access, review, audit trails, retention and incident response." };
const controls = [
  { icon: UserCheck, title: "Contributor vetting", text: "Identity and profile review, skills assessment, task qualification and project-specific onboarding." },
  { icon: KeyRound, title: "Controlled access", text: "Role-based permissions, minimum necessary access, workforce restrictions and clear offboarding." },
  { icon: Fingerprint, title: "Confidentiality", text: "Contributor agreements, project confidentiality terms and handling instructions appropriate to the work." },
  { icon: FileClock, title: "Traceable activity", text: "Task history, review decisions, exception logs and delivery records where the project environment supports them." },
  { icon: ShieldAlert, title: "Escalation", text: "Defined routes for ambiguous data, policy concerns, quality failures and suspected security incidents." },
  { icon: RefreshCcw, title: "Continuity", text: "Capacity planning, contributor replacement, knowledge capture and recovery procedures aligned to the engagement." },
];
const faq = [{ question: "Which compliance certifications do you hold?", answer: "We do not publish certification claims until they are formally verified. During procurement, we provide an accurate description of current operational controls and available evidence." }, { question: "Can contributor access be region restricted?", answer: "Yes. Region, language, experience and access restrictions can be included in the contributor profile and enforced during allocation." }, { question: "How is quality measured?", answer: "Measures vary by task and may include gold-task performance, reviewer acceptance, agreement, correction rates, rubric distributions and issue severity. The measurement plan is agreed before production." }, { question: "What happens when a contributor falls below standard?", answer: "Responses may include coaching, recalibration, increased review, temporary pause, reassignment or removal. A replacement path is maintained for critical roles." }];
export default function QualityPage() { return <main><SiteHeader /><PageIntro eyebrow="Quality & security" title="Controls buyers can understand—and delivery teams can operate." text="We translate project risk into practical contributor, access, review and governance controls. Formal claims remain subject to legal and security review." /><section className="section controls-grid">{controls.map((control) => { const Icon = control.icon; return <article key={control.title}><Icon size={27} /><h2>{control.title}</h2><p>{control.text}</p></article>; })}</section><section className="quality-lifecycle"><div><p className="eyebrow eyebrow-light">Quality lifecycle</p><h2>Prevent, detect, correct and learn.</h2></div><div>{["Prevent", "Detect", "Correct", "Improve"].map((title, index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{["Clear criteria, suitable contributors and calibration.", "Sampling, review signals and performance monitoring.", "Issue triage, rework and contributor intervention.", "Guideline updates, feedback and recurring-error analysis."][index]}</p></article>)}</div></section><section className="section security-checklist"><div><p className="eyebrow">Procurement-ready topics</p><h2>The questions your risk team is likely to ask.</h2><p>Engagement documentation can cover the applicable controls, responsibilities and limitations.</p></div><div>{["Identity verification approach", "Qualification and calibration", "Data access and permissions", "Confidentiality agreements", "Secure file exchange", "Audit trails and escalation", "Retention and deletion", "Incident response", "Regional restrictions", "Business continuity"].map((item) => <span key={item}><Check size={16} /> {item}</span>)}</div></section><FaqBlock items={faq} title="Straight answers for security and procurement teams." /><section className="simple-cta"><div><p className="eyebrow eyebrow-light">Discuss project risk early</p><h2>Security works best when it shapes the workflow.</h2></div><Link className="button button-light" href="/contact">Request a consultation <ArrowRight size={17} /></Link></section><SiteFooter /></main>; }
